management:
  endpoints.web:
    base-path: /management
    exposure.include: '*'
  server.port: 9090

server:
  connection-timeout: 30000ms
  port: 8081
  servlet.context-path: /

logging:
  path: ./
  file: st.log
  #max-size: 10M
  #max-history: 1
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
    com:
      wxx:
        modules:
          st:
            mapper: DEBUG

master:
  name: EvanDevyml
  sex: nv
  subject: chi
  phone: 111

destination:
  topic: st.student.update


openmq:
  brokerIpAddressList: localhost:7676,localhost:7677
